# Generated by Django 3.2.9 on 2022-04-06 19:33

from django.db import migrations


def create_users(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    User = apps.get_model("db", "User")
    if not User.objects.using(db_alias).filter(id=-1).count():
        User.objects.using(db_alias).create(id=-1, user_id=100, current_state="none", role_id=5)
    if not User.objects.using(db_alias).filter(id=1).count():
        User.objects.using(db_alias).create(id=1, user_id=309253224, current_state="none", role_id=5)
    if not User.objects.using(db_alias).filter(id=2).count():
        User.objects.using(db_alias).create(id=2, user_id=190252554, current_state="none", role_id=5)


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0003_user'),
    ]

    operations = [
        migrations.RunPython(create_users),
    ]
