# Generated by Django 3.2.12 on 2022-04-13 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_remove_user_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
