# Generated by Django 3.2.12 on 2022-04-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
